// src/theme.js
export const themeColors = {

  light: {
    topbarBg: "bg-white",
    topbarBorder: "border-white",
    bottomNav: "bg-white",
    bottomNavIconActive: "btn-dark",
    settingDivider:"border-light",
    cartItemBg:'bg-light',
    productBorder: 'border-0 shadow',
    backgroundHome:'#ffffff', 
    background: "#f8f9fa",        // page background
    cardBg: "#fff",               // card background
    text: "text-dark",            // main text
    textSecondary: "text-secondary", 
    textMuted: "text-muted",
    badgeBg: "bg-warning",
    badgeText: "text-dark",
    btnPrimary: "btn-warning",
    btnText: "text-dark",
    iconDefault: "text-gray",
    iconActive: "text-danger",
    scrollBarBg: "#fff",
    catSelected:"btn-dark",
    catUnselected:"btn-light",
    inputBg:"#fff",
    inputTxtColor:"#000",
    searchBtnBg:"bg-dark",
    searchIconColor:"text-light",
    listClass:"bg-light border-2 border-white",
    bgLi:'bg-light',
    txtLi:'text-dark',
    modalPic:'bg-white',
    sideBarBg:'bg-light',
    modalBtnStyle:'',
    modalCountStyle:'',
    modalHeaderBorder:'',
    aboutPrdBadge:' border text-black',
    totalBillBg:'bg-light border',
    checkoutBtn:'btn-dark',
    cartTopBarBg:'white',
  },

  dark: {
    topbarBg: "bg-dark",
    topbarBorder: "border-dark",
    bottomNav: "bg-dark",
    bottomNavIconActive: "btn-active",
    settingDivider:"border-dark",
    cartItemBg:'bg-dark',
    backgroundHome:'#121212',
    productBorder: 'border-0',
    background: "#121212",
    cardBg: "#1e1e1e",
    text: "text-light",
    textSecondary: "text-light",
    textMuted: "text-light",
    badgeBg: "bg-warning",
    badgeText: "text-dark",
    btnPrimary: "btn-warning",
    btnText: "text-dark",
    iconDefault: "text-secondary",
    iconActive: "text-danger",
    scrollBarBg: "#1e1e1e",
    catSelected:"btn-warning",
    catUnselected:"btn-outline-warning",
    inputBg:"#2c2c2c",
    inputTxtColor:"#fff",
    searchBtnBg:"bg-warning",
    searchIconColor:"text-dark",
    listClass:"bg-dark border-2 border-bg",
    bgLi:'bg-dark',
    txtLi:'text-light',
    modalPic:'bg-black',
    sideBarBg:'bg-dark',
    modalCountStyle:'bg-dark border border-secondary text-white',
    modalBtnStyle:'bg-black text-white border border-secondary',
    modalHeaderBorder:'border-black',
    aboutPrdBadge:'bg-dark text-white',
    totalBillBg:'bg-dark border border-secondary',
    checkoutBtn:'btn-light',
    cartTopBarBg:'#121212',
  },
};
